version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  app:
    image: webapp:latest  
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay  
volumes:
  db_data:
